[package]
name = "dioxus-web"
version = { workspace = true }
authors = ["Jonathan Kelley"]
edition = "2021"
description = "Web renderer for Dioxus using websys"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com/learn/0.5/getting_started"
keywords = ["dom", "ui", "gui", "react", "wasm"]

[dependencies]

dioxus-core-types = { workspace = true }
dioxus-core = { workspace = true }
dioxus-html = { workspace = true }
dioxus-document = { workspace = true }
dioxus-devtools = { workspace = true }
dioxus-signals = { workspace = true }
dioxus-interpreter-js = { workspace = true, features = [
    "minimal_bindings",
    "webonly",
] }
generational-box = { workspace = true }

async-trait = { workspace = true }
ciborium = { workspace = true, optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
futures-channel = { workspace = true }
futures-util = { workspace = true, features = [ "async-await", "async-await-macro" ] }
js-sys = "0.3.56"
rustc-hash = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
serde-wasm-bindgen = { version = "0.6.5", optional = true }
tracing = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = "0.4.29"

[dependencies.web-sys]
version = "0.3.56"
features = [
    "AnimationEvent",
    "ClipboardEvent",
    "Comment",
    "CompositionEvent",
    "console",
    "CustomEvent",
    "DataTransfer",
    "Document",
    "DragEvent",
    "FocusEvent",
    "HtmlElement",
    "HtmlHeadElement",
    "HtmlFormElement",
    "HtmlInputElement",
    "HtmlSelectElement",
    "HtmlTextAreaElement",
    "InputEvent",
    "KeyboardEvent",
    "MouseEvent",
    "NodeList",
    "PointerEvent",
    "ResizeObserverEntry",
    "ResizeObserverSize",
    "Text",
    "Touch",
    "TouchEvent",
    "TouchList",
    "TransitionEvent",
    "WheelEvent",
    "Window",
]


[build-dependencies]
lazy-js-bundle = { workspace = true }

[features]
default = ["panic_hook"]
full = [
    "devtools",
    "mounted",
    "file-engine",
    "document"
]
panic_hook = ["dep:console_error_panic_hook"]

hydrate = ["web-sys/Comment", "ciborium", "dep:serde"]
mounted = ["web-sys/Element", "dioxus-html/mounted"]
file-engine = [
    "dioxus-html/file-engine",
    "web-sys/File",
    "web-sys/FileList",
    "web-sys/FileReader"
]
devtools = [
    "web-sys/MessageEvent",
    "web-sys/WebSocket",
    "web-sys/Location",
    "dep:serde_json",
    "dep:serde",
    "dioxus-core/serialize",
]
document = [
    "dep:serde-wasm-bindgen",
    "dep:serde_json",
    "dep:serde",
]

[dev-dependencies]
dioxus = { workspace = true, default-features = true }
wasm-bindgen-test = "0.3.29"
dioxus-ssr = { workspace = true, default-features = false }
gloo-timers = { workspace = true }
dioxus-web = { path = ".", features = ["hydrate"] }
tracing-wasm = "0.2.1"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
