[package]
name = "dioxus-html"
version = { workspace = true }
authors = ["Jonathan Kelley"]
edition = "2021"
description = "HTML Element pack for Dioxus - a concurrent renderer-agnostic Virtual DOM for interactive user experiences"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["dom", "ui", "gui", "react"]

[dependencies]
dioxus-core = { workspace = true }
dioxus-core-types = { workspace = true }
dioxus-rsx = { workspace = true, optional = true }
dioxus-html-internal-macro = { workspace = true }

serde = { version = "1", features = ["derive"], optional = true }
serde_repr = { version = "0.1", optional = true }
euclid = "0.22.7"
enumset = "1.1.2"
keyboard-types = { version = "0.7", default-features = false }
async-trait = { version = "0.1.58", optional = true }
serde_json = { version = "1", optional = true }
tracing.workspace = true

futures-channel = { workspace = true }

# dioxus-core = { workspace = true }
# generational-box = { workspace = true }
# todo: we shouldn't have any wasm-bindgen dependencies in the html cratea
# [target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm-bindgen = { workspace = true, optional = true }
# js-sys = { version = "0.3.56", optional = true }
# wasm-bindgen-futures = { workspace = true, optional = true }

[build-dependencies]
lazy-js-bundle = { workspace = true }

[dev-dependencies]
serde_json = "1"
dioxus = { workspace = true }
dioxus-web = { workspace = true }
tokio = { workspace = true, features = ["time"] }
manganis = { workspace = true }

[features]
default = ["serialize", "mounted", "file-engine"]
serialize = [
    "dep:serde",
    "dep:serde_json",
    "dep:serde_repr",
    "euclid/serde",
    "keyboard-types/serde",
    "dioxus-core/serialize"
]
mounted = [
    # "web-sys?/Element",
    # "web-sys?/DomRect",
    # "web-sys?/ScrollIntoViewOptions",
    # "web-sys?/ScrollLogicalPosition",
    # "web-sys?/ScrollBehavior",
    # "web-sys?/HtmlElement",
]
file-engine = [
    "dep:async-trait",
    # "dep:js-sys",
    # "web-sys?/File",
    # "web-sys?/FileList",
    # "web-sys?/FileReader"
]
hot-reload-context = ["dep:dioxus-rsx", "dioxus-rsx/hot_reload_traits"]
html-to-rsx = []

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
feature = ["html-to-rsx", "hot-reload-context", "html-to-rsx"]
